"""
List of allt the events used
"""

events = {
    "CREATE_TASK": "CREATE_TASK",
    "JOIN": "JOIN",
    "NEW_TASK": "NEW_TASK",
    "GET_NEW_TASK": "GET_NEW_TASK",
    "TASK_ACCEPTED": "TASK_ACCEPTED",
    "TASK_DECLINED": "TASK_DECLINED",
    "TASK_CANCELLED": "TASK_CANCELLED",
    "TASK_COMPLETED": "TASK_COMPLETED",
    "TASK_PENDING": "TASK_PENDING",

    "TASK_CANCELLED_ACK": "TASK_CANCELLED_ACK",
    "TASK_COMPLETED_ACK": "TASK_COMPLETED_ACK",
    "TASK_DECLINED_ACK": "TASK_DECLINED_ACK",
    "TASK_DECLINED_ACK_SM": "TASK_DECLINED_ACK_SM",

    "LIST_STATES": "LIST_STATES",
    "LIST_STATES_REPLY": "LIST_STATES_REPLY",
    "UPDATE_STATE": "UPDATE_STATE"
}
