events = {
    "CREATE_TASK": "CREATE_TASK",
    "JOIN": "JOIN",
    "NEW_TASK": "NEW_TASK",
    "TASK_ACCEPTED": "TASK_ACCEPTED",
    "TASK_DECLINED": "TASK_DECLINED",
    "TASK_CANCELLED": "TASK_CANCELLED",
    "TASK_PENDING": "TASK_PENDING",
    "TASK_COMPLETED": "TASK_COMPLETED",
    "TASK_COMPLETED_ACK": "TASK_COMPLETED_ACK",
    "TASK_DECLINED_ACK": "TASK_DECLINED_ACK"
}