# Generated by Django 2.2.1 on 2019-05-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190525_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytask',
            name='title',
            field=models.CharField(max_length=180, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='deliverytask',
            unique_together=set(),
        ),
    ]
