# Generated by Django 2.2.1 on 2019-05-25 08:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20190525_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytask',
            name='title',
            field=models.CharField(db_index=True, max_length=180),
        ),
        migrations.AlterUniqueTogether(
            name='deliverytask',
            unique_together={('title', 'created_by')},
        ),
    ]
