# Generated by Django 2.2.1 on 2019-05-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='low', max_length=10)),
                ('creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'DeliveryTask',
                'verbose_name_plural': 'DeliveryTasks',
            },
        ),
    ]
