# Generated by Django 2.2.1 on 2019-05-22 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverytask',
            old_name='state',
            new_name='states',
        ),
    ]
