# Generated by Django 2.2.1 on 2019-05-22 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190522_0433'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deliverystatetransition',
            unique_together={('task', 'state')},
        ),
    ]
