# Generated by Django 2.2.1 on 2019-05-18 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_deliverytask_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverytask',
            old_name='creation',
            new_name='creation_at',
        ),
    ]
