# Generated by Django 2.2.1 on 2019-05-22 18:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20190522_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytaskstate',
            name='state',
            field=models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='new', max_length=12),
        ),
        migrations.AlterUniqueTogether(
            name='deliverystatetransition',
            unique_together={('task', 'state', 'by')},
        ),
    ]
