# Generated by Django 2.2.1 on 2019-05-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190518_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytask',
            name='title',
            field=models.CharField(max_length=180, unique=True),
        ),
    ]
