# Generated by Django 2.2.1 on 2019-05-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190525_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytaskstate',
            name='state',
            field=models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], db_index=True, default='new', max_length=12, unique=True),
        ),
    ]
