# Generated by Django 2.2.1 on 2019-05-18 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20190518_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverytaskstate',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_delivery_person': True, 'is_storage_manager': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to_dp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'is_delivery_person': False, 'is_storage_manager': True}, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_sm', to=settings.AUTH_USER_MODEL),
        ),
    ]
